In [9]:
# import numpy as np 

import numpy as np
import matplotlib.pyplot as plt

In [25]:
# Dimensionalidad de los array

escalar = np.array(5)
vector = np.array(np.random.randint(0,10,10))
matriz = np.array(np.random.randint(0,10,[4,4]))
tensor = np.array(np.random.randint(0,10,[2,4,4]))

escalar.ndim, vector.ndim, matriz.ndim, tensor.ndim

(0, 1, 2, 3)

In [ ]:
escalar * vector # operación vectorizada

[i*2 for i in [1,2,3,4,5]]

array([10, 40, 35, 25, 15, 40, 45,  0, 40, 10])

In [24]:
matriz, matriz.shape

(array([[2, 0, 1, 1],
        [9, 3, 1, 7],
        [2, 1, 0, 7],
        [2, 5, 6, 6]], dtype=int32),
 (4, 4))

In [26]:
tensor, tensor.shape

(array([[[9, 1, 6, 7],
         [0, 5, 3, 5],
         [2, 3, 0, 8],
         [1, 4, 1, 0]],
 
        [[6, 3, 1, 2],
         [9, 2, 7, 1],
         [8, 3, 8, 8],
         [6, 8, 2, 5]]], dtype=int32),
 (2, 4, 4))

In [13]:
s = np.random.randint(25,100,100) + np.random.random()
type(s), s.shape, s.ndim

(numpy.ndarray, (100,), 1)

In [28]:
np.random.choice(s,2)

array([44.49243266, 68.49243266])

In [35]:
# Ejemplo de tirada de moneda

lanzamiento = ['Cara','Cruz']
muestra = np.random.choice(lanzamiento,100)

In [ ]:
muestra.values_count()

In [40]:
v = np.array(list(range(10)))
type(v), v

(numpy.ndarray, array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [39]:
np.array([list(range(5))], dtype = 'float64')

array([[0., 1., 2., 3., 4.]])

In [44]:
np.arange(1,10,2)
np.linspace(0,10,12)

array([ 0.        ,  0.90909091,  1.81818182,  2.72727273,  3.63636364,
        4.54545455,  5.45454545,  6.36363636,  7.27272727,  8.18181818,
        9.09090909, 10.        ])

In [48]:
np.random.rand(4,4)
x = np.random.randint(1,15,(4,4))

In [51]:
x.shape
x_transformado = x.reshape(2,8)
x_transformado

array([[ 2, 10,  8,  2,  4, 12,  1,  3],
       [ 7,  4,  9,  7,  6,  3, 13,  8]], dtype=int32)

In [52]:
matriz = np.random.randint(0,20,[10,10])
matriz

array([[ 2, 17,  9,  8,  9,  5, 12,  9, 19, 15],
       [12, 12,  2,  7, 11, 10, 18,  7, 17,  6],
       [ 6,  8, 17,  2,  1, 13, 11, 12,  3,  7],
       [11,  7,  8, 16, 10,  9,  2, 14,  8,  6],
       [ 4,  2, 10,  5, 14, 12, 19,  9,  8,  3],
       [16, 12, 18,  4, 14, 13,  9,  4, 10,  7],
       [ 5,  2, 18,  7,  8, 10,  4,  3,  9, 16],
       [12,  9,  5, 12, 10, 11, 13, 18, 12,  7],
       [10, 19,  6, 16,  1,  8,  7, 14, 19, 19],
       [18,  6,  8, 13,  0,  7,  1, 13, 15,  8]], dtype=int32)

In [55]:
np.mean(matriz)
np.median(matriz)
np.std(matriz)

np.float64(5.028916384272063)

In [63]:
matriz[-3:,[1,3,-1]]

array([[ 9, 12,  7],
       [19, 16, 19],
       [ 6, 13,  8]], dtype=int32)

# Para casa
1. Cree una matriz de 8 por 8 de valores enteros aleatorios entre 0 y 20

2. Cree un nuevo objeto que sea la misma matriz pero con 4 columnas

3. Acceda a la posición (6,4) de la matriz 1

4. Acceda a la posición (16,4) de la matriz 1

5. Acceda a la matriz subconjunto de la matriz 1 que va de la fila 5 a la 8 y de la columna 3 a la 7.

6. Cree un vector aleatorio de 60 elementos entre 0 y 100. Asuma que es un vector de edades de una muestra. Calcule la medidas de estadisticas e interprete.
